---
# tasks file for subscribe-sat
- name: Add Satellite server IP
  lineinfile:
    path: /etc/hosts
    line: '{{ sat_ip }}  {{ satellite }}'
    create: yes
- name: Pull and Install katello-ca
  block:
    - name: Pull cert
      get_url:
        url: "http://{{ satellite }}/pub/katello-ca-consumer-latest.noarch.rpm"
        dest: /tmp/katello-ca-consumer-latest.noarch.rpm
        mode: '0440'
    - name: Install cert on STIG'd machines
      command: "/usr/bin/rpm -i --nodigest --nofiledigest /tmp/katello-ca-consumer-latest.noarch.rpm"
      ignore_errors: True
- name: Subscribe RHEL 7 servers
  redhat_subscription:
    state: present
    activationkey: '{{ satKey7 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "7"
- name: Subscribe RHEL 8 servers
  redhat_subscription:
    state: present
    activationkey: '{{ satKey8 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "8"
- name: Subscribe RHEL 8 servers
  redhat_subscription:
    state: present
    activationkey: '{{ satKey9 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "9"
- name: Install Cockpit on RHEL 7
  yum:
    name: cockpit
    state: present
  when: ansible_facts['distribution_major_version'] == "7"
- name: Start Cockpit
  systemd:
    name: cockpit.socket
    enabled: yes 
- name: Update to latest
  yum:
    name: "*"
    state: latest
- name: Reboot
  reboot:
   reboot_timeout: 120
