---
# tasks file for idm-dns_ad_setup
- name: Set DNS forwardzone for AD
  ipadnsforwardzone:
    ipaadmin_password: "{{ admin_password }}"
    state: present
    name: "{{ ad_domain }}"
    forwarders:
      - ip_address: "{{ ad_ip }}"
    forwardpolicy: only
    skip_overlap_check: true
#- name: Wait for sync
#  wait_for:
#    timeout: 60
- name: Configure AD trust
  ipatrust:
    ipaadmin_password: "{{ admin_password }}"
    realm: "{{ ad_domain }}"
    admin: delegate
    password: "{{ ad_password }}"
    state: present
