---
# tasks file for idm-
- name: Create hostsgroup for clients
  ipahostgroup:
    ipaadmin_password: "{{ admin_password }}"
    name: "{{ host_group }}"
    description: "Client servers"
    host:
    - "{{ inventory_hostname }}"