---
# Please read the README.md file
- name: Configure Windows
  hosts: win
  become_method: runas
  become_user: Administrator
  become: False
  roles:
    - role: winCreate
      state: present
    - role: winUsers
      state: present
    - role: winDelegate
      state: present
  tags: win
- name: Configure Users
  hosts: all:!win
  become: True
  roles:
  - role: local_users
  tags: locUsers
## Need to choose which method to update systems with.
- name: Subscribe systems to RH CDN
  hosts: all
  become: True
  roles:
  - role: subscribe-cdn
  tags: cdn
- name: Subscribe systems to local satellite
  hosts: all:!win
  become: True
  roles:
  - role: subscribe-sat
  tags: satloc
- name: Update nameserver entry on ipareplcas and ipaclients
  hosts: all:!ipaserver:!win:!others
  become: true
  roles:
  - role: rhel-system-roles.network
    vars:
      crypto_policies_policy: "DEFAULT:AD-SUPPORT"
      crypto_policies_reboot_required: True
- name: Update Crypto policy for AD Trust
  hosts: ipaserver:ipareplicas
  become: true
  roles:
  - role: rhel-system-roles.crypto_policies
## Must have the ansible-freeipa rpm package installed.
- name: Installs the IdM server
  import_playbook: /usr/share/doc/ansible-freeipa/playbooks/install-server.yml
- name: Turn IdM DNS PTR Sync on
  hosts: ipaserver
  gather_facts: false
  become: false
  roles:
  - role: idm-dnsconfig
    state: present
- name: Installs the IdM replicas
  import_playbook: /usr/share/doc/ansible-freeipa/playbooks/install-replica.yml
  tags: replica
- name: Installs the IdM clients
  import_playbook: /usr/share/doc/ansible-freeipa/playbooks/install-client.yml
  tags: clients
- name: Sets up the AD trust.
  hosts: ipaserver
  gather_facts: false
  become: True
  roles:
  - role: idm-dns_ad_setup
  tags: adtrust
- name: Create IdM users
  hosts: ipaserver
  gather_facts: false
  become: True
  roles:
  - role: idm-users
  tags: idmUsers
- name: Create external group for AD Users/Groups
  hosts: ipaserver
  gather_facts: false
  become: True
  roles:
  - role: idm-groups
  tags: idmGrps
- name: Create client host group
  hosts: ipaserver
  gather_facts: false
  become: false
  roles:
  - role: idm-hostgroup
  tags: hostGrp
- name: Create HBAC Rules
  hosts: ipaserver
  gather_facts: false
  become: False
  roles:
  - role: idm-hbac
  tags: hbac
- name: Enable sudo on clients
  hosts: ipaclients
  gather_facts: false
  become: true
  roles:
  - role: sudo-sssd
  tags: sudo
- name: Create IdM SUDO rules
  hosts: ipaserver
  gather_facts: false
  become: False
  roles:
  - role: idm-sudo
  tags: sudo