---
# tasks file for local_users
- name: Copy ssh-keys
  authorized_key:
    user: "{{ local_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key }}') }}"
- name: Add user
  user:
    name: "{{ item.luser_name }}"
    comment: "{{ item.luser_full }}"
    shell: "/bin/bash"
    password: "{{ item.luser_pass }}"
    groups: 
    - wheel
    append: yes
  with_items: "{{ addlocal_user }}"