---
# tasks file for subscribe-cdn
- name: Subscribe to CDN Satellite
  redhat_subscription:
    state: present
    username: "{{ satCDN_user }}"
    password: "{{ satCDN_passwd }}"
- name: Disable all repositories
  rhsm_repository:
    name: '*'
    state: disabled
- name: Enable RHEL 7 repositories
  rhsm_repository:
    name: rhel-7-server-rpms
    state: enabled
  when: ansible_facts['distribution_major_version'] == "7"
- name: Enable RHEL 8 repositories
  rhsm_repository:
    name: rhel-8-for-x86_64-baseos-rpms,rhel-8-for-x86_64-appstream-rpms
    state: enabled
  when: ansible_facts['distribution_major_version'] == "8"
- name: Install Cockpit on RHEL 7
  yum:
    name: cockpit
    state: present
  when: ansible_facts['distribution_major_version'] == "7"
- name: Start Cockpit
  systemd:
    name: cockpit.socket
    enabled: yes 
- name: Update to latest
  yum:
    name: "*"
    state: latest
- name: Reboot
  reboot:
   reboot_timeout: 120
