---
# tasks file for idm-dns_names
- name: Generate DNS entries in IdM
  ipadnsrecord:
    ipaadmin_password: "{{ admin_password }}"
    zone_name: local.example.com
    records:
    - name: host-{{ item }}
      cname_hostname: idm.local.example.com
    - name: server-{{ item }}
      cname_hostname: idm.local.example.com
  with_sequence: count=5000 