---
# tasks file for idm-ad-group
- name: Create External Group for AD group
  ipagroup:
    ipaadmin_password: "{{ admin_password }}"
    name: extadusergrp
    description: "External group for AD Users"
    external: yes
    externalmember: 
      - '{{ ad_grp_name }}@{{ ad_domain }}'
    state: present
- name: Create Internal group for External AD group
  ipagroup:
    ipaadmin_password: "{{ admin_password }}"
    name: intextadgrp
    description: "Internal group for External AD group"
    group:
      - extadusergrp
    state: present
- name: Create IdM admins group
  ipagroup:
    ipaadmin_password: "{{ admin_password }}"
    name: idmadmins
    description: "IdM group for admins"
    state: present
- name: Added useres to IdM admins group
  ipagroup:
    ipaadmin_password: "{{ admin_password }}"
    name: idmadmins
    action: member
    user:
    - "{{ item.idm_name }}"
  with_items: "{{ idm_users }}"
