---
# tasks file for dns-resolve
- name: Update resolv.conf with IdM master IP
  command: '/bin/nmcli con mod {{ ansible_default_ipv4.alias }} ipv4.dns {{ idm_DNS1 }}'
- name: Restart interface
  command: '/bin/nmcli con up {{ ansible_default_ipv4.alias }}'